#ifndef USER_PROTOCOL_FRAME_DEFINES_H_
#define USER_PROTOCOL_FRAME_DEFINES_H_

#define FRAME_HEADER_SIZE 4*4   // four 32 bit words
#define DATAGRAM_HEADER_SIZE 12*4

#define FRAME_TYPE_POS 3

#define FSGP_COMMAND_FRAME 3
#define FSGP_ACK_FRAME 4
#define UPPM_COMMAND_FRAME 5
#define UPPM_ACK_FRAME 5
#define UPPM_FDK_FRAME 15
#define FSGP_FDK_FRAME 16

#define COMMAND_DATA_POS FRAME_HEADER_SIZE+DATAGRAM_HEADER_SIZE

#endif /* USER_PROTOCOL_FRAME_DEFINES_H_ */
