#ifndef USER_PROTOCOL_FRAME_DEFINES_H_
#define USER_PROTOCOL_FRAME_DEFINES_H_

#define FRAME_TYPE_POS 3

#define COMMAND_FRAME 3
#define ACK_FRAME 4
#define FDK_FRAME 16

#endif /* USER_PROTOCOL_FRAME_DEFINES_H_ */
