#ifndef USER_PROTOCOL_FRAME_DEFINES_H_
#define USER_PROTOCOL_FRAME_DEFINES_H_

#define LOW_WORD_OFFSET 3

#define WORD128_BYTE_SIZE 4

#define FRAME_HEADER_SIZE 4*WORD128_BYTE_SIZE   // four 32 bit words
#define DATAGRAM_HEADER_SIZE 12*WORD128_BYTE_SIZE

// Fields positions---------------------------------
#define CTRL_OFFSET128_LW 4*WORD128_BYTE_SIZE + LOW_WORD_OFFSET
#define CTRL_SIZE128_LW 5*WORD128_BYTE_SIZE + LOW_WORD_OFFSET

#define SYNC_OFFSET128_LW 6*WORD128_BYTE_SIZE + LOW_WORD_OFFSET
#define SYNC_SIZE128_LW 7*WORD128_BYTE_SIZE + LOW_WORD_OFFSET

#define HEAD_AUX_OFFSET128_LW 8*WORD128_BYTE_SIZE + LOW_WORD_OFFSET
#define HEAD_AUX_SIZE128_LW 9*WORD128_BYTE_SIZE + LOW_WORD_OFFSET

#define SIGNAL_OFFSET128_LW 10*WORD128_BYTE_SIZE + LOW_WORD_OFFSET
#define SIGNAL_SIZE128_LW 11*WORD128_BYTE_SIZE + LOW_WORD_OFFSET
//--------------------------------------------------
#define HEADER_FRAME_TYPE_POS 3
#define BODY_FRAME_TYPE_POS 19

#define FSGP_COMMAND_FRAME 3
#define FSGP_ACK_FRAME 4
#define UPPM_COMMAND_FRAME 5
#define UPPM_ACK_FRAME 6
#define UPPM_FDK_FRAME 15
#define FSGP_FDK_FRAME 16

#define COMMAND_DATA_POS FRAME_HEADER_SIZE+DATAGRAM_HEADER_SIZE

#endif /* USER_PROTOCOL_FRAME_DEFINES_H_ */
