#ifndef USER_PROTOCOL_UPPM_RAW_COMM_FRAME_H_
#define USER_PROTOCOL_UPPM_RAW_COMM_FRAME_H_

#include <stdint.h>
#include "frame_defines.h"


// Fields value
#define UPPM_RAW_COMM_FRAME_CTRL_OFFSET128 3
#define UPPM_RAW_COMM_FRAME_CTRL_SIZE128 1

#define UPPM_RAW_COMM_FRAME_SYNC_OFFSET128 4
#define UPPM_RAW_COMM_FRAME_SYNC_SIZE128 0

#define UPPM_RAW_COMM_FRAME_AUX_DATA_OFFSET128 4
#define UPPM_RAW_COMM_FRAME_AUX_DATA_SIZE128 0

#define UPPM_RAW_COMM_FRAME_SIGNAL_OFFSET128 4
#define UPPM_RAW_COMM_FRAME_SIGNAL_SIZE128 0


#endif /* USER_PROTOCOL_UPPM_RAW_COMM_FRAME_H_ */
